# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1547, 920)
        MainWindow.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cpu_frame = QtWidgets.QFrame(self.centralwidget)
        self.cpu_frame.setGeometry(QtCore.QRect(10, 20, 310, 571))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cpu_frame.setFont(font)
        self.cpu_frame.setAutoFillBackground(False)
        self.cpu_frame.setStyleSheet("border-width:2px;\n"
"border-color: rgb(0, 243, 255);\n"
"border-style:inset;\n"
"")
        self.cpu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cpu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_frame.setObjectName("cpu_frame")
        self.cpu_label = QtWidgets.QLabel(self.cpu_frame)
        self.cpu_label.setGeometry(QtCore.QRect(110, 10, 81, 54))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.cpu_label.setFont(font)
        self.cpu_label.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width: 0px;")
        self.cpu_label.setObjectName("cpu_label")
        self.cpu_usage = QtWidgets.QLabel(self.cpu_frame)
        self.cpu_usage.setGeometry(QtCore.QRect(20, 60, 181, 63))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cpu_usage.setFont(font)
        self.cpu_usage.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width:0px")
        self.cpu_usage.setObjectName("cpu_usage")
        self.cpu_speed = QtWidgets.QLabel(self.cpu_frame)
        self.cpu_speed.setGeometry(QtCore.QRect(20, 110, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cpu_speed.setFont(font)
        self.cpu_speed.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width:0px")
        self.cpu_speed.setObjectName("cpu_speed")
        self.cpu_temp_label = QtWidgets.QLabel(self.cpu_frame)
        self.cpu_temp_label.setGeometry(QtCore.QRect(70, 150, 181, 63))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cpu_temp_label.setFont(font)
        self.cpu_temp_label.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width: 0px;")
        self.cpu_temp_label.setObjectName("cpu_temp_label")
        self.cpu_temp = QtWidgets.QLabel(self.cpu_frame)
        self.cpu_temp.setGeometry(QtCore.QRect(20, 210, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cpu_temp.setFont(font)
        self.cpu_temp.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width:0px")
        self.cpu_temp.setObjectName("cpu_temp")
        self.min_cpu_temp = QtWidgets.QLabel(self.cpu_frame)
        self.min_cpu_temp.setGeometry(QtCore.QRect(20, 262, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.min_cpu_temp.setFont(font)
        self.min_cpu_temp.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width:0px")
        self.min_cpu_temp.setObjectName("min_cpu_temp")
        self.max_cpu_temp = QtWidgets.QLabel(self.cpu_frame)
        self.max_cpu_temp.setGeometry(QtCore.QRect(20, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.max_cpu_temp.setFont(font)
        self.max_cpu_temp.setStyleSheet("color: rgb(0, 243, 255);\n"
"border-width:0px")
        self.max_cpu_temp.setObjectName("max_cpu_temp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hardware Monitor"))
        self.cpu_label.setText(_translate("MainWindow", "CPU"))
        self.cpu_usage.setText(_translate("MainWindow", "Usage: 0%"))
        self.cpu_speed.setText(_translate("MainWindow", "Speed: 0 MHz"))
        self.cpu_temp_label.setText(_translate("MainWindow", "Temperature"))
        self.cpu_temp.setText(_translate("MainWindow", "Value:"))
        self.min_cpu_temp.setText(_translate("MainWindow", "Min:"))
        self.max_cpu_temp.setText(_translate("MainWindow", "Max:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
